from flask import Flask
from flask_wtf.csrf import CSRFProtect
from .routes.home import home_bp
import threading
import time
import logging
from pathlib import Path


def create_app(config_object=None):
    """
    Create and configure the Flask application.

    Args:
        config_object: Optional configuration object.

    Returns:
        Flask app: Configured Flask application instance.
    """
    app = Flask(__name__, static_folder="static", template_folder="templates")

    # Minimal configuration (extensible)
    if config_object:
        app.config.from_object(config_object)

    # Initialize CSRF protection
    csrf = CSRFProtect(app)

    # Register blueprints
    app.register_blueprint(home_bp)

    # Create upload directory if it doesn't exist
    upload_dir = app.config.get('UPLOAD_FOLDER')
    if upload_dir and not upload_dir.exists():
        upload_dir.mkdir(parents=True, exist_ok=True)

    # Start background cleanup thread to remove old generated videos
    def _cleanup_temp_videos(temp_dir_path, max_age_seconds=3600, interval_seconds=600):
        logger = logging.getLogger(__name__)
        try:
            temp_path = Path(temp_dir_path)
        except Exception:
            logger.exception("Invalid temp directory for cleanup")
            return

        while True:
            try:
                now = time.time()
                for f in temp_path.iterdir():
                    try:
                        if not f.is_file():
                            continue
                        # target mp4 files generated by the app
                        if f.suffix.lower() != '.mp4':
                            continue
                        age = now - f.stat().st_mtime
                        if age > max_age_seconds:
                            f.unlink(missing_ok=True)
                            logger.info(f"Removed old temp video: {f}")
                    except Exception:
                        logger.exception(f"Failed to inspect or remove temp file {f}")
            except Exception:
                logger.exception("Error during temp video cleanup loop")
            time.sleep(interval_seconds)

    # Do not start cleanup in testing mode
    try:
        if not app.config.get('TESTING', False):
            temp_dir = Path().resolve().joinpath('tmp')
            # Prefer system temp dir; fall back to project tmp
            import tempfile as _tmp
            system_tmp = Path(_tmp.gettempdir())
            cleanup_dir = system_tmp if system_tmp.exists() else temp_dir
            t = threading.Thread(target=_cleanup_temp_videos, args=(str(cleanup_dir),), daemon=True)
            t.start()
    except Exception:
        logging.getLogger(__name__).exception('Failed to start temp cleanup thread')

    return app
